# Generated by Django 5.2 on 2025-04-22 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
