# Generated by Django 5.2 on 2025-04-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_estudante_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
